Aparking/BaseConocimiento

Docusaurus/classic/docs/Planificación proyecto/Condiciones De Fallos Check.md
Referente a la issue #155 del Backend
=> Doc: Failure Condition Check

Docusaurus/classic/docs/Planificación proyecto/Customer Agreement.md, Docusaurus/classic/docs/Sprint 2/Evaluación del rendimiento de los usuarios piloto.md
Performance evaluation de los usuarios pilotos del grupo 5. Aprobaba por el coordinador @3ralon
=> Doc: Evaluacion usuarios piloto

Docusaurus/classic/docs/Sprint 2/11-Sprint-Retrospective-2.md
Hace referencia a la issue https://github.com/Aparking/AparKing_Backend/issues/140
Tarea realizada por @virolialo y revisada por @laurolmer
=> Inserción del Sprint Retrospective

Docusaurus/classic/docs/Sprint 2/11-Sprint-Review-2.md
Esta pull request hace referencia a la tarea: https://github.com/Aparking/AparKing_Backend/issues/139
=> Adición del Sprint Review (corregido)

Docusaurus/classic/docs/Sprint 2/11-revision.md
=> Doc: Software Revision fixed

Docusaurus/classic/docs/Sprint 3/11-Planning-Test.md
Documento de plan de pruebas del proyecto, esto es una primera versión la cual deberá de ser actualizada en el caso en el que algún integrante del grupo haya vaya a realizar un tipo de prueba o vaya a usar una herramienta distinta de las que se definen en este doc
=> Doc: Planning Test

Docusaurus/classic/docs/Sprint 3/11-Risks-Analysis.md
Se han añadido nuevos riesgos pertinentes y se han actualizado otros riesgos.
=> Análisis de riesgos semana del 09/04 al 15/04

Docusaurus/classic/docs/Sprint 3/11-Sprint-Review-3.md
Se ha realizado el documento de Sprint Review correspondiente al tercer sprint, con la colaboración de @3ralon.
=> docs: Sprint Review S3

Docusaurus/classic/docs/Sprint 3/11-Sprint-Planning-Marketing.md
Hemos realizado el sprint planning de la siguiente etapa de Marketing.
Colaborador: @3ralon
=> docs: Add Sprint Planning

Docusaurus/classic/docs/Planificación proyecto/PerfomanceEvaluation.md
Añadido el performance evaluation mio y de pedro ya que no entre en el srpint anterior del drive
=> fix: added s2 performance evaluation of Pedro and José

Docusaurus/classic/docs/Sprint 3/11-Sprint-Retrospective-3.md
Hemos realizado el documento que recoge el Sprint Retrospective realizado en el sprint 3.
Colaborador: @3ralon
=> docs: Add sprint retrospective s3

Docusaurus/classic/docs/Planificación proyecto/PerfomanceEvaluation.md
He edito la tabla de versiones para tener el registro de las distintas modificaciones por sprint. He añadido mi evaluación del S3 y además le he puesto al resto de compañeros las semanas pertenecientes a este Sprint para facilitar su correcta cumplimentación. 
Dejo la rama abierta para que otro compañeros puedan usarla a la hora de rellenar el documento.
=> Add evaluation to S3

Docusaurus/classic/docs/Planificación proyecto/PerfomanceEvaluation.md
He añadido la parte de performance evaluation de mi compañero @sergiosant02 .
=> doc: Add performance evaluation Sergio

Docusaurus/classic/docs/Planificación proyecto/PerfomanceEvaluation.md
Algunas tareas se habían tabulado erróneamente y lo he corregido.
=> Refactor task format

Docusaurus/classic/docs/Planificación proyecto/Justification_HTTP.md
Se ha añadido un documento explicando los motivos de porque en nuestro proyecto no hemos implementado HTTPS.
=> Add justification

Docusaurus/classic/docs/Sprint 3/InformationProvidedByPilotUsers.md
Se ha añadido una sección sobre el feedback recibido de los usuarios pilotos externos, es decir, aquellos que no pertenecen a NextONG
=> Feedback de usuarios pilotos externos

Docusaurus/classic/docs/AI-usage/ChatGPT.md
He añadido una nueva entrada de reporte de IA al documento.
=> doc: ia report 

Docusaurus/classic/docs/Planificación proyecto/pilotUsersCommitmentAgreement.md
=> Add new clause about how to use the anonymous data

Docusaurus/classic/docs/Planificación proyecto/PerfomanceEvaluation.md, Docusaurus/classic/docs/Sprint 2/11-revision.md, Docusaurus/classic/docs/Sprint 3/11-revision.md, Docusaurus/classic/docs/intro.md
Añadida mi información relativa al Performance Evaluation de este entregable.
=> doc: performance evaluation

Docusaurus/classic/docs/PPL/11-revision.md
Faltaba la agrupación por description
=> Fix url clockify PPL
